### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by andymerrick** [kylegregory/EmmaSharp#19]
Hey bro... thanks so much for this library... saved me a ton of time!

Real quick, the NuGet package is out-of-date because it doesn't include the changes you made to Int32 on the member object to handle large ids. I ended up just dl'ing the library and compiling it locally, but thought you'd want to know in case you didn't. Again, thanks, man!

**Comment by kylegregory** [comment]
Hey @andymerrick,

Thanks for the issue. Was aware of the fact that the package was out of date with the repo. The change I made was a breaking change, so I wanted some folks to test out the code before I pushed it live as a release, hence the change is still in the HEAD and not a full release.

Unfortunately, as OSS goes, I haven't had time myself to test the change. I quickly implemented the code change and moved on to the next project.

If you have the code running and seems to work, then I'll be happy to push a new release so it's up on NuGet. It's definitely easier to keep up with code changes in your projects than pulling the source for each release.

Thanks,
Kyle

**Comment by andymerrick** [comment]
Totally understand what you're saying about time. This library was a huge help. I DO have the code running in production right now (actually, on an Azure WebJob that runs every morning) and it's been working perfectly for the last three mornings. Making a few calls to /mailings, /members, and /response and aggregating data. Having the new code as a package would most def be appreciated. The old download/compile method of yesteryear is a chore. We've become spoiled by our tools! Thankfully so! Thanks once more for making this and offering it, man.

**Comment by kylegregory** [comment]
Released: 1.0.1: You should be able to see the EmmaSharp package in NuGet soon, @andymerrick.
