### ISSUE TITLE
Update Custom Contact field that is a multi checkbox field

### ISSUE THREAD

**Issue by eddiejbrady** [kylegregory/EmmaSharp#24]
Hi, I can't seem to figure out how to update a custom field which is a multi select checkbox field.  Would you know how to do this?

This is what I have at the moment.  Note, that the "interests" column is a custom multi checkbox column

            var memberBulk = emails.Select(e => new EmmaSharp.Models.MemberBulk
            {
                MemberEmail = e,
                Fields = new Dictionary<string, string> {
                    { "interests", "{advocacy}" },
                    { "newcustomfield", "TestUpdate5" }
                }
            }).ToList();

            var members = new EmmaSharp.Models.AddMembers()
            {
                AddOnly = false
            };
            members.Members.AddRange(memberBulk);

Any help would be appreciated.

Thanks.

**Comment by kylegregory** [comment]
Hey @eddiejbrady so Fields here is a Dictionary type with string key and value. What I would do is override the base class for your use. I wrote up some untested code that might help you get in the right direction.

            //Your new class definition inheriting MemberBulk
            public class MemberBulkArray : MemberBulk
             {
                [JsonProperty("fields")]
                public new Dictionary<string, object> Fields { get; set; }
                public MemberBulkArray()
                {
                   MemberEmail = MemberEmail;
                   Fields = Fields;
                }
            }

            //Your call to the API.
            var emails = new string[] { "test@test.com", "test2@test.com" };

            var memberBulk = emails.Select(e => new MemberBulkArray
            {
                MemberEmail = e,
                Fields = new Dictionary<string, object> {
                { "interests", new string[] {"Hunting", "Fishing", "Camping" } },
                { "newcustomfield", "TestUpdate5" }
            }
            }).ToList();

            var members = new AddMembers()
            {
                AddOnly = false
            };
            members.Members.AddRange(memberBulk);

Let me know if that works for you. I'll consider a change to the wrapper to object so it can handle string array for fields, but it will be breaking to do so.

**Comment by kylegregory** [comment]
Fixed in https://github.com/kylegregory/EmmaSharp/commit/bc6420faf1c2b02ffa90cd8a4567c8c47f376d02
