### ISSUE TITLE
GetMailing doesn't bind RecipientGroups 

### ISSUE THREAD

**Issue by sabmah** [kylegregory/EmmaSharp#25]
According to the API **/#account_id/mailings/#mailing_id**, the data returned has an array object "recipient_groups". It has two properties "member_group_id" and "name" . When **GetMailing(memberId)** is used, only MemberId is binded and not rest of the Group properties.

**Comment by kylegregory** [comment]
Hey @sabmah looks like you have run across a number of naming inconsistencies in the API. I've pushed a fix for this in the repo and it will be incorporated into a upcoming release. Thanks!
