### ISSUE TITLE
Time lag between "AddNewMembers" and "ListGroupMembers".

### ISSUE THREAD

**Issue by tjdavis1111** [kylegregory/EmmaSharp#26]
I am adding emails to MEMBERS and GROUPS.  Once added, I perform a LISTGROUPMEMBERS as I need to retrieve the MEMBERIDs that have been created.  However, there appears to be a time lag between the "ADD" and what gets listed.

In the example below, I am adding a fifth email to the group.  While the EMMA UI correctly displays the 5 members, the LISTGROUPMEMBERS only retrieves 4.  If I wait a while and then reissue the LISTGROUPMEMBERS, I get all 5.

What am I doing wrong.?

![addmembers](https://user-images.githubusercontent.com/17165109/27772342-b05c3654-5f25-11e7-9077-41e586a21496.png)

**Comment by kylegregory** [comment]
Through my testing it looks like requests are cached for around 300 seconds (5 minutes). Varnish returns the "age" header and you can see it resets for any call around 300 seconds or so. So that might be what you're running into.

Does that seem to be the case?
Kyle
