### ISSUE TITLE
EMMA API Dropping Support for TLS 1.0

### ISSUE THREAD

**Issue by tjdavis1111** [kylegregory/EmmaSharp#27]
Kyle, 
Per the following, EMMA is dropping support for TLS 1.0 on 8/1/2017.  They recommend implementing TLS 1.2.
https://community.myemma.com/emma/topics/emma-api-no-longer-supporting-tls-1-0-as-of-august-1st-2017

Given that all of my calls to the API are via EMMASharp, I don't believe that I have control over the level of TLS that is used.  

Will you be releasing a version of EMMASharp that supports TLS 1.2?

I am current using EMMASharp V1.0.6379.31443.

**Comment by tjdavis1111** [comment]
Kyle,
I added the following to my .NET 4.5.2 app and all is good.

        System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
        System.Net.ServicePointManager.SecurityProtocol &= ~SecurityProtocolType.Tls;

**Comment by kylegregory** [comment]
@tjdavis1111 If my understanding is correct, HttpWebRequest (which RestSharp uses) is similar in a browser request in that when the connection is made, the Requesting server (browser) and the Endpoint server negotiate the highest level of security that each one allows/supports. In this case, if your request supports TLS 1.2, it will automatically take that one as it is highest first. The override you did just says that you won't support anything other thanTLS 1.2 or TLS 1.0 (your second option).

This will get you TLS 1.1 and higher.

        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;

I'm more surprised at the quick turnaround on the change.
