### ISSUE TITLE
TLS 1.0 no longer supported

### ISSUE THREAD

**Issue by KieraAtkins** [kylegregory/EmmaSharp#29]
Hi We have been using EmmaSharp for a few months and suddenly it stopped working on the 8/16 and after further investigating Emma stopped supporting TSL 1.0 on the same day. here is a link to the blog https://community.myemma.com/emma/topics/emma-api-no-longer-supporting-tls-1-0-as-of-august-1st-2017
So my question is this also uses restsharp as well so one of these library's needs to be updated.

**Comment by kylegregory** [comment]
Fixed in https://github.com/kylegregory/EmmaSharp/commit/bc6420faf1c2b02ffa90cd8a4567c8c47f376d02
