### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by CarsonHager** [kylegregory/EmmaSharp#30]
Not sure if this is the right place for this but are you guys considering support for .NET Core? I'm getting errors saying something it's not supported on the current platform.

Thanks,

Carson

**Comment by CarsonHager** [comment]
This is the contents of the exception - Serializing delegates is not supported on this platform.

**Comment by CarsonHager** [comment]
I ended up getting this to work by using RestSharp.NetCore and making some changes to the Execute() method of EmmaApi.

**Comment by kylegregory** [comment]
@CarsonHager RestSharp is the culprit. Don't really have time to investigate a replacement. I'm glad RestSharp.NetCore works, but isn't a public repo and isn't being actively updated as well.

**Comment by CarsonHager** [comment]
I definitely spoke too soon. Although the first few things worked, I’m running into additional issues now. Fun, Fun, Fun.
