### ISSUE TITLE
.GetMailingSends method fails when field is defined as "check_multiple"

### ISSUE THREAD

**Issue by tjdavis1111** [kylegregory/EmmaSharp#31]
The full text of the bug is in the attached image.
![emmabug](https://user-images.githubusercontent.com/17165109/31253691-701ce6c2-a9eb-11e7-9ada-3304a8deb8f0.png)

**Comment by tjdavis1111** [comment]
I am running EmmaSharp V1.0.5

**Comment by kylegregory** [comment]
@tjdavis1111 Update to the latest version of EmmaSharp (currently 1.1.0). All "Field" properties were updated to List<string, object> to handle these scenarios.

See #28

**Comment by tjdavis1111** [comment]
Thx.
