### ISSUE TITLE
AddMemberToGroups

### ISSUE THREAD

**Issue by pbhandari1s** [kylegregory/EmmaSharp#34]
I am looking for an option to use this wrapper on one of my big projects that includes email management. I am confused with this method AddMemberToGroups which expects memberid and List<int> as members. I am passing the same thing but getting error saying unable to parse json request, which I am assuming is because of integers. Can you help verify if this method is working?

P.S. I just started today, so I might be confused too.

This is how I am using it.

```
        public bool AddContactToMailingList(string emailAddress, List<int> groupIds)
        {
            try
            {
                var emmaApi = EmmaApiConfig();

                var memberInfo = emmaApi.GetMemberByEmail(emailAddress);
                string memberId = memberInfo.MemberId.ToString();
               
                EmmaSharp.Models.Members.MemberGroups groups = new EmmaSharp.Models.Members.MemberGroups
                {
                    GroupIds = groupIds
                };

                emmaApi.AddMemberToGroups(memberId, groups);

                return true;
            }

            catch (Exception ex)
            {
                var exception = ex;
                return false;
            }
            
        }
```

**Comment by kylegregory** [comment]
I think the method is missing the JSON Serializer, so the body is formatted correctly. Thanks for the heads up. I'll push an update and the fix will be included in a future release.
