### ISSUE TITLE
AddNewMembers Failing with JSON integer 4939648906 is too large or small for an Int32. Path 'import_id', line 2, position 25.

### ISSUE THREAD

**Issue by tjdavis1111** [kylegregory/EmmaSharp#35]
I am trying to execute an "AddNewMembers" command but am receiving the following error.  This is my third installation but it is the only one that is failing.

This code runs successfully with two other EMMA clients.  I have included the "GetImportInformation" of a successful run at the end of this note. 

Please note that this is of extremely high priority as my client needs to send their EMMA campaign this week (i.e., 4/2/2018).

Thank you.

--------------------------------------
**ERROR MESSAGE:**
JSON integer 4939648906 is too large or small for an Int32. Path 'import_id', line 2, position 25.

--------------------------------------
**SOFTWARE VERSIONS:** 
	EmmaSharp: 1.1.0
	Newtonsoft.Json: 11.0.2

--------------------------------------
**CODE:**
	//--------------------------------------
	// Create EMMA Members and add to Group
	//--------------------------------------
	List<MemberBulk> Members = new List<MemberBulk>();
	foreach (var contact in contactsWithEmails)
	{
		MemberBulk memberBulk = new MemberBulk();
		memberBulk.MemberEmail = contact.Email;
		//V1.1.0
		Dictionary<string, object> fields = new Dictionary<string, object>();
		fields.Add(settings.FirstNameFieldName, contact.FirstName);
		fields.Add(settings.LastNameFieldName, contact.LastName);
		fields.Add(settings.InterActionIdFieldName, contact.Id.ToString());
		memberBulk.Fields = fields;
		Members.Add(memberBulk);
	}
	AddMembers addMembers = new AddMembers();
	addMembers.AddOnly = false;
	addMembers.Members = Members;
	addMembers.GroupIds = new List<Int32>() { Convert.ToInt32(focGroupID) };
	MembersAdd membersAdd = emmasharp.AddNewMembers(addMembers);

--------------------------------------
**OBJECT VALUES:**
-		Members	Count = 3	System.Collections.Generic.List<EmmaSharp.Models.MemberBulk>
	-		[0]	{EmmaSharp.Models.MemberBulk}	EmmaSharp.Models.MemberBulk
		-		Fields	Count = 3	System.Collections.Generic.Dictionary<string, object>
			+		[0]	{[first_name, Steve]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[1]	{[last_name, xxx]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[2]	{[InterActionID, F2i2]}	System.Collections.Generic.KeyValuePair<string, object>	
			MemberEmail	"sxxx@xxx.com"	string
	-		[1]	{EmmaSharp.Models.MemberBulk}	EmmaSharp.Models.MemberBulk
		-		Fields	Count = 3	System.Collections.Generic.Dictionary<string, object>
			+		[0]	{[first_name, Shelley]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[1]	{[last_name, xxx]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[2]	{[InterActionID, F2i129]}	System.Collections.Generic.KeyValuePair<string, object>	
			MemberEmail	"sxxx@xxx.com"	string
	-		[2]	{EmmaSharp.Models.MemberBulk}	EmmaSharp.Models.MemberBulk
		-		Fields	Count = 3	System.Collections.Generic.Dictionary<string, object>
			+		[0]	{[first_name, Colleen]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[1]	{[last_name, xxx]}	System.Collections.Generic.KeyValuePair<string, object>
			+		[2]	{[InterActionID, F2i202]}	System.Collections.Generic.KeyValuePair<string, object>	
			MemberEmail	"cxxx@xxx.com"	string

-		focGroupID	"4031370"	string

--------------------------------------
**STACK TRACE:**
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at EmmaSharp.EmmaApi.Execute[T](RestRequest request, Int32 start, Int32 end)
   at EmmaSharp.EmmaApi.AddNewMembers(AddMembers members)
   at INTCS.InterAction.DotNET.Api.INTCSContacts.sendContactsToEMMA(Folder folder, Contact folderOnlyContact, String groupIdMailingId, AppSettings settings, EmmaApi emmasharp, MailingType mailType) in C:\LNGOAKTFSA001\EKH_S\INTCS.EMMA.Integration\INTCS.InterAction.DotNET.Api\INTCSContacts.cs:line 767
	 
--------------------------------------
**SUCCESSFUL EXECUTION WITH A DIFFERENT EMMA CLIENT:**  
[GetImportInformation}
Results of ImportId: 42572062
{
  "import_id": 42572062,
  "status": "o",
  "style": "add_and_update",
  "import_started": "@D:2018-04-02T20:29:38",
  "account_id": 1796382,
  "error_message": null,
  "num_members_updated": 0,
  "source_filename": null,
  "fields_updated": [
    {
      "shortcut_name": "first_name",
      "account_id": null,
      "required": false,
      "field_id": 766238,
      "short_display_name": null,
      "deleted_at": null,
      "options": null,
      "display_name": "First name",
      "field_type": "text",
      "widget_type": "text",
      "column_order": null
    },
    {
      "shortcut_name": "last_name",
      "account_id": null,
      "required": false,
      "field_id": 767262,
      "short_display_name": null,
      "deleted_at": null,
      "options": null,
      "display_name": "Last name",
      "field_type": "text",
      "widget_type": "text",
      "column_order": null
    },
    {
      "shortcut_name": "interactionid",
      "account_id": null,
      "required": false,
      "field_id": 792862,
      "short_display_name": null,
      "deleted_at": null,
      "options": null,
      "display_name": "InterActionID",
      "field_type": "text",
      "widget_type": "text",
      "column_order": null
    }
  ],
  "num_members_added": 1,
  "import_finished": "@D:2018-04-02T20:29:39",
  "groups_updated": [
    {
      "active_count": null,
      "deleted_at": null,
      "error_count": null,
      "optout_count": null,
      "group_type": "g",
      "member_group_id": 5661982,
      "purged_at": null,
      "account_id": null,
      "group_name": "Wiss Emma Integration Demo (2018-04-02 20:27)"
    }
  ],
  "num_skipped": 0,
  "num_duplicates": 0
}

**Comment by tjdavis1111** [comment]
To further determine where the error lay, I coded up a POSTMAN example:

**POST:**
https://api.e2ma.net/xxxxx/members

**BODY:**
{
	"members": [
	{
		"email": "csoliman@xxx.com",
		"fields": {
			"first_name": "Colleen",
			"last_name": "Soliman",
			"interactionid": "F2i202"
		}
	},
	{
		"email": "sjaworski@xxx.com",
		"fields": {
			"first_name": "Steve",
			"last_name": "Jaworski",
			"interactionid": "F2i2"
		}
	},
	{
		"email": "slazarescu@xxx.com",
		"fields": {
			"first_name": "Shelley",
			"last_name": "Lazarescu",
			"interactionid": "F2i129"
		}
	}
	],
	"add_only": false,
	"group_ids": [xxxx]
}

**RESPONSE:**
{
    "import_id": 4941417354
}

**Comment by kylegregory** [comment]
@tjdavis1111 

Thanks for the heads up. That should be long in order to catch for that large of an ID. I don't have time currently to push an update, but do know that's on my list to fix soon.

**Comment by MilSix** [comment]
Hi Kyle,
Quick questions for you about Emma api :

Is there an emma api calls for bulk “archive” subaccount/group/ of members ?

I only see there are 3 member statuses:  “active”, “error”, or “optout” . Is there a way to set a member to “Inactive” ?

**Comment by kylegregory** [comment]
This was fixed in 1a4cfd4d449771bd86c5ab3414791da019eb68ca

@MilSix question moved to a new issue.
