### ISSUE TITLE
New Import Status

### ISSUE THREAD

**Issue by MikeSmithDev** [kylegregory/EmmaSharp#40]
Recently been receiving the following error: Newtonsoft.Json.JsonSerializationException: Error converting value "q" to type 'System.Nullable`1[EmmaSharp.Models.Members.ImportStatus]'. 

After contacting Emma, this was their response:

The 'q' status indicates that the import is queued in the system. This status was recently added to give users more insight into the import's progress. Previously, the API would return the value of 'null' when the import had been added but not processed.

This status should resolve relatively quickly to `o` or `e` and is more likely to occur when performing multiple imports into the same account.

**Comment by cheezewhizze** [comment]
I did not see this error happening until the past week (4/2/19), but I have it now, too. enum needs to include "q"
