### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException - Self referencing loop detected

### ISSUE THREAD

**Issue by johnkuefler** [kylegregory/EmmaSharp#43]
Calling any method is giving me the following error:
```
'Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path 'OnBeforeDeserialization.Method.Module.Assembly'.'
```

This appears to be related to serializing/tracing each request. (Line 68, EmmaSharp.cs):
```
Trace.WriteLine(request.JsonSerializer.Serialize(request));
```

Removing the trace allows method calls to work again. This seems like debug type functionality, I wonder if a flag could be added to disable it, or it could be disabled altogether? Happy to open a PR to address it.

**Comment by kylegregory** [comment]
@johnkuefler Sounds like there is a circular reference is somewhere in the code when we are deserializing the call. Can you let me know what method you're calling, so I can look at the data structure?

**Comment by johnkuefler** [comment]
Ok so I was working in a .net core console app and getting this error for any api call in that context, I assume due to the age of some of the project dependencies. Working in a .net framework console app I did not receive any errors. I was able to get this to work for my project (the .net core console app) by downloading and including the project directly as a reference, updating newtonsoft json and restsharp to the latest version, removing the Trace.Writeline call mentioned above., and updating it to .net framework 4.7.2. So I guess a non-issue here. It would be nice to have this project updated to target .net standard, but that's a separate issue that I'm sure would take some significant effort.

Thanks for your time, this library is making the project I'm working on much easier!

**Comment by kylegregory** [comment]
@johnkuefler Agreed. Project references need to be updated. I was holding out for RestSharp to hit v107 so that it depends once again on Json.Net, then updating both. Yes, I haven't migrated to .Net Standard, but happy to receive any assistance in that respect. Thanks for the update.

**Comment by johnkuefler** [comment]
@kylegregory I might open an issue relating to migrating this to .net standard since I've got some experience working with the library now and make a PR in the next several weeks if I have any success. I think that would be very helpful to consumers of the library. Thanks!
